### ISSUE TITLE
Black strip displays at top of map when choosing a new feature on data grid.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/meridian#517] opened 2015-01-27 17:59 UTC
This happens on develop branch
STR-
Run a query
Open data grid
Choose a feature row
RESULTS - The feature pop up details displays on map. Dark strip appears at the top of map then goes away.  Every. 5th or 6th time.
EXPECTED RESULTS - The feature pop up details displays on map. Dark strip SHOULD NOT appear at the top of map. Ever.

**Comment by cwilmsen** [comment] 2015-01-29 13:56
I do not see this problem, and thus cannot do anything.

**Comment by tdressel** [comment] 2015-02-02 20:28
I cannot repro this.

**Comment by tdressel** [comment] 2015-02-02 20:28
Cannot repro on develop.

**Comment by jlfoster2** [comment] 2015-02-02 20:30
Cant reproduce...closing ticket

**Comment by jlfoster2** [comment] 2015-02-02 20:30
Closing...can reproduce bug

**Closed by jlfoster2** 2015-02-02 20:30 UTC
Labels: 0 - Backlog, Bug
